### ISSUE TITLE
Google.com is kind of intrusive.

### ISSUE THREAD

**Issue by IshanArya** [manojVivek/medium-unlimited#6]
Hi. Intercepting cookies from Google.com seems kind of intrusive and unsafe. Can you please justify your reasoning or provide a way to disable access to Google.com?

**Comment by manojVivek** [comment]
Hey @IshanArya 
Below is the reason for the new permission request.

The extension was failing to unlock content for external publisher articles for which the content is hosted in their own website and not in Medium. A few extension users were not happy because of this(check the recent reviews).
So, I released a new feature to fix this problem. Whenever an external publisher article is detected, the extension performs a google search with the article title and identifies the original link for the article and displays it for the user to open and read.

More precisely, this google search is performed in an isolated way, not to be associated with the google user currently logged in the browser. The permission is required specifically to achieve this.

Sample external publisher article - https://medium.com/fast-company/the-worst-design-crimes-of-2018-56f32b027bb7

The permission is more to removing user cookies in the extension's search request, so it will not belong to the Google user logged in the browser at all. So it's actually for a good cause but looks otherwise.

**Comment by IshanArya** [comment]
Wow, okay. Thank you for explaining that.
