### ISSUE TITLE
Auto removed from Chrome

### ISSUE THREAD

**Issue by SwiftyWang** [manojVivek/medium-unlimited#66]
Very nice plugin but one some issue.

I drag this chrome extension to chrome://extension, it works fine. But after my mac reboot, this extension missing again. Now I need to drag to install again.
Does anyone know what happened?
PS: the other extensions won't have this problem.

**Comment by manojVivek** [comment]
Hey @SwiftyWang,
After you add the extension, you cannot delete the folder where you extracted the extension. 
If you delete that folder, the extension will disappear when you restart the browser.

**Comment by SwiftyWang** [comment]
I didn't extract the folder just drag the zip file to chrome://extension

**Comment by manojVivek** [comment]
Oh, I think since you drag and drop it, it is internally extracting it to a temporary path and using it. That is causing it to disappear after the restart. 

Can you try extracting it first and then loading that folder?
You can see here to the steps if required - https://manojvivek.github.io/medium-unlimited/download/

**Comment by SwiftyWang** [comment]
After extract seems won't auto uninstall thanks.
